# Scoring and LLM configuration for Enhanced Hotel AI Screener

# Enable LLM full-text review so ChatGPT reads every resume and re-ranks results
llm:
  full_review_enabled: true
  # Model and runtime settings
  model: gpt-4o-mini
  temperature: 0.1
  timeout: 45          # seconds
  chunk_chars: 6000    # characters per chunk for long resumes
  # Rate-limit & stability controls
  requests_per_minute: 6       # start conservatively; will ramp when stable
  cooldown_on_429_secs: 45     # longer cooldown to avoid repeated 429s
  max_concurrent: 1            # keep at 1 to avoid bursty 429s
  max_chunks_per_resume: 2     # cap LLM chunks per resume; 0 disables the cap
  max_retries: 0               # SDK retries (we manage our own backoff)
  disable_on_error: false      # do not disable LLM for rate limits; only for repeated hard errors if you enable this
  # Advanced pacing
  dynamic_throttle_on_429: true
  min_requests_per_minute: 1
  max_requests_per_minute: 12
  adaptive_ramp_up: true
  ramp_up_step: 2
  stable_window_secs: 90
  cooldown_progress_step_secs: 5
  persist_rpm: true
  # Batch ranking (reduces API calls and rate limits)
  batch_mode_enabled: true
  batch_size: 4
  snippet_chars: 800
  top_n: 15
  batch_only_over: 10
  abort_on_rate_limit: false

# Embeddings fallback (when sentence-transformers unavailable)
embeddings:
  enable_fallback: true   # use TF-IDF similarity if embedding model is missing

# Optional: adjust category weights globally (will be normalized)
# weights:
#   experience: 0.35
#   skills: 0.30
#   cultural_fit: 0.20
#   hospitality: 0.15
