[global]
developmentMode = false

[server]
port = 8501
# Keep secure defaults to avoid mixed warnings
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"

[client]
# Removed deprecated/invalid option to silence warnings
